# Configuration for the Labeler GitHub action, executed by
# .github/workflows/labeler.yml.
#
# The basic syntax is [label]: [path patterns].
#
# For more details on the configuration please see:
# https://github.com/marketplace/actions/labeler

# For example:
#
# "part:module":
#   - changed-files:
#     - any-glob-to-any-file:
#       - "src/frequenz/lib/setuptools_betterproto/module/**"
#
# "part:other":
#   - changed-files:
#     - any-glob-to-any-file:
#       - "src/frequenz/lib/setuptools_betterproto/other/**"
#
# # For excluding some files (in this example, label "part:complicated"
# # everything inside src/ with a .py suffix, except for src/__init__.py)
# "part:complicated":
#   - all:
#     - changed-files:
#       - any-glob-to-any-file:
#         - "src/**/*.py"
#       - all-glob-to-all-file:
#         - "!src/__init__.py"
#
# Please have in mind that that the part:xxx labels need to
# be created in the GitHub repository.

"part:docs":
  - changed-files:
    - any-glob-to-any-file:
      - "**/*.md"
      - "docs/**"
      - "examples/**"
      - LICENSE

"part:tests":
  - changed-files:
    - any-glob-to-any-file:
      - "**/conftest.py"
      - "tests/**"

"part:tooling":
  - changed-files:
    - any-glob-to-any-file:
      - "**/*.ini"
      - "**/*.toml"
      - "**/*.yaml"
      - "**/*.yml"
      - "**/conftest.py"
      - ".editorconfig"
      - ".git*"
      - ".git*/**"
      - "docs/*.py"
      - CODEOWNERS
      - MANIFEST.in
      - noxfile.py

"part:codegen":
  - all:
    - changed-files:
      - any-glob-to-any-file:
        - "src/setuptools_betterproto/**/*.py"
      - all-globs-to-all-files:
        - "!**/conftest.py"
